    
    personal_information:
      name: "[Your Name]"
      surname: "[Your Surname]"
      date_of_birth: "[Your Date of Birth]"
      country: "[Your Country]"
      city: "[Your City]"
      address: "[Your Address]"
      phone_prefix: "[Your Phone Prefix]"
      phone: "[Your Phone Number]"
      email: "[Your Email Address]"
      github: "[Your GitHub Profile URL]"
      linkedin: "[Your LinkedIn Profile URL]"
    
    summary:
      - description: [Your summary]
    
    education_details:
      - education_level: "[Your Education Level]"
        institution: "[Your Institution]"
        field_of_study: "[Your Field of Study]"
        final_evaluation_grade: "[Your Final Evaluation Grade]"
        start_date: "[Start Date]"
        year_of_completion: "[Year of Completion]"
        exam:
          exam_name_1: "[Grade]"
          exam_name_2: "[Grade]"
          exam_name_3: "[Grade]"
          exam_name_4: "[Grade]"
          exam_name_5: "[Grade]"
          exam_name_6: "[Grade]"
    
    experience_details:
      - position: "[Your Position]"
        company: "[Company Name]"
        employment_period: "[Employment Period]"
        location: "[Location]"
        industry: "[Industry]"
        key_responsibilities:
          - responsibility_1: "[Responsibility Description]"
          - responsibility_2: "[Responsibility Description]"
          - responsibility_3: "[Responsibility Description]"
        skills_acquired:
          - "[Skill]"
          - "[Skill]"
          - "[Skill]"
    
      - position: "[Your Position]"
        company: "[Company Name]"
        employment_period: "[Employment Period]"
        location: "[Location]"
        industry: "[Industry]"
        key_responsibilities:
          - responsibility_1: "[Responsibility Description]"
          - responsibility_2: "[Responsibility Description]"
          - responsibility_3: "[Responsibility Description]"
        skills_acquired:
          - "[Skill]"
          - "[Skill]"
          - "[Skill]"
    
    projects:
      - name: "[Project Name]"
        description: "[Project Description]"
        link: "[Project Link]"
    
      - name: "[Project Name]"
        description: "[Project Description]"
        link: "[Project Link]"
    
    achievements:
      - name: "[Achievement Name]"
        description: "[Achievement Description]"
      - name: "[Achievement Name]"
        description: "[Achievement Description]"
    
    certifications:
      - name: "[Certification Name]"
        description: "[Certification Description]"
      - name: "[Certification Name]"
        description: "[Certification Description]"
    
    languages:
      - language: "[Language]"
        proficiency: "[Proficiency Level]"
      - language: "[Language]"
        proficiency: "[Proficiency Level]"
    
    interests:
      - "[Interest]"
      - "[Interest]"
      - "[Interest]"
    
    availability:
      notice_period: "[Notice Period]"
    
    salary_expectations:
      salary_range_usd: "[Salary Range]"
    
    self_identification:
      gender: "[Gender]"
      pronouns: "[Pronouns]"
      veteran: "[Yes/No]"
      disability: "[Yes/No]"
      ethnicity: "[Ethnicity]"
    
    legal_authorization:
      eu_work_authorization: "[Yes/No]"
      us_work_authorization: "[Yes/No]"
      requires_us_visa: "[Yes/No]"
      requires_us_sponsorship: "[Yes/No]"
      requires_eu_visa: "[Yes/No]"
      legally_allowed_to_work_in_eu: "[Yes/No]"
      legally_allowed_to_work_in_us: "[Yes/No]"
      requires_eu_sponsorship: "[Yes/No]"
    
    work_preferences:
      remote_work: "[Yes/No]"
      in_person_work: "[Yes/No]"
      open_to_relocation: "[Yes/No]"
      willing_to_complete_assessments: "[Yes/No]"
      willing_to_undergo_drug_tests: "[Yes/No]"
      willing_to_undergo_background_checks: "[Yes/No]"